trainer: energy

dataset:
  - src: ../ocp_datasets/data/is2re/100k/train/data.lmdb
    normalize_labels: True
    target_mean: -1.525913953781128
    target_std: 2.279365062713623
  - src: ../ocp_datasets/data/is2re/all/val_ood_both/data.lmdb
  - src: ../ocp_datasets/data/is2re/all/test_ood_both/data.lmdb

logger: tensorboard

task:
  dataset: single_point_lmdb
  description: "Relaxed state energy prediction from initial structure."
  type: regression
  metric: mae
  labels:
    - relaxed energy
